### ISSUE TITLE
URLs contains baseurl + full url permalink 

### ISSUE THREAD

**Issue by robertmuehsig** [jekyll/jekyll-seo-tag#178]
I discovered that the seo plugin produce wrong URLs and I'm not sure if I did something wrong from the configuration side.

Currently something like this is generated:

```
  <!-- Begin Jekyll SEO tag v2.1.0 -->
<title>Server Installation</title>
<meta property="og:title" content="Server Installation" />
<link rel="canonical" href="http://docs.oneoffixx.com/http://docs.oneoffixx.com/install/de/server/" />
<meta property="og:url" content="http://docs.oneoffixx.com/http://docs.oneoffixx.com/install/de/server/" />
<script type="application/ld+json">
{"@context": "http://schema.org",
"@type": "WebPage",
"headline": "Server Installation",
"url": "http://docs.oneoffixx.com/http://docs.oneoffixx.com/install/de/server/"}</script>
<!-- End Jekyll SEO tag -->
```

As you can see the plugin will generates something like this: http://docs.oneoffixx.com/http://docs.oneoffixx.com/

The configuration looks like this:

```
# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "LICENSE.txt", "_stage"]
highlighter: 'rouge' 

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
include: ['_pages']

baseurl: http://docs.oneoffixx.com
github_repo_url: https://github.com/OneOffixx/docs/

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
```

And a typical page has this yaml:

```
---
layout: page
title: Übersicht
permalink: "concepts/de/overview/"
---
```

How do I get rid of the double URLs?

(notice that I disable the plugin on our site because of this issue) The site is hosted on [GitHub](https://github.com/Sevitec/oneoffixx-docs)
