### ISSUE TITLE
Add option to prevent using site description for og:description

### ISSUE THREAD

**Issue by ahmetb** [jekyll/jekyll-seo-tag#219]
When a particular does not have a `description`, SEO plugin uses the site description in _config.yml as `og:description`. This is not a great idea, as both Facebook and Twitter can extract the main content from a page's HTML.

If this plugin offers a way to disable using site’s main description for all pages in `og:description`, that would be great. 

You can see this issue in action at https://kubernetes.io/docs/reference/client-libraries/ (validator: https://cards-dev.twitter.com/validator) (source: https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/reference/client-libraries.md)

**Comment by benbalter** [comment]
Would it make more sense to implement support for page excerpts in Jekyll core?

**Comment by ahmetb** [comment]
I'm not familiar with the inner workings of the project. Seems like there's already support for excerpts: https://jekyllrb.com/docs/posts/ If available, it would be nice to have it used instead of og:description.

That said, if you omit og:description, FB/Twitter etc will do almost an equally good job extracting the relevant content.

**Comment by 7php** [comment]
@ahmetb , on the page concerned, in your front-matter, set `description: " "` ?

**Comment by ahmetb** [comment]
@7php sounds like an overkill (or not quite the right solution to do) when you have 500 pages contributed by 800+ people on a daily basis. :)

**Comment by mmistakes** [comment]
@7php you can use front matter defaults in your `_config.yml` and set for all posts.

https://jekyllrb.com/docs/configuration/#front-matter-defaults

**Comment by ahmetb** [comment]
@mmistakes Hmm I tried the following in `_config.yaml`

```yaml
defaults:
  -
    scope:
      path: ""
    values:
      description: ""
      # ....other variables below....
      fullversion: "v1.7.0"
      version: "v1.7"
      githubbranch: "master"
      docsbranch: "master"

```

I'm still getting `og:description` meta tag with value that's in `description:` key of `_config.yaml`

In case you're interested in taking a look, the site is at https://github.com/kubernetes/kubernetes.github.io.

**Comment by mmistakes** [comment]
What about `description: " "` with a space like @7php suggested above?

**Comment by 7php** [comment]
hi guys,
I have tried the defaults in front-matter, here are my observations:

1) description: " " # with a space does not work unfortunately

2) I had to "fake" the space with `&nbsp;` as follows: 
```
defaults:
  -
    scope:
      path: "" # apply to all paths
    values:
      #layout: "default" # commenting this out so that it applies to all layouts
      description: "&nbsp;" # will output: <meta property="og:description" content=" ">
```

3) Another approach is to use an "**IF**" statement in your **layouts**, so that **IF NOT description**, then simply output: `<meta property="og:description" content="">`

Hope that can help..

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least two months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider whether it can be accomplished in another way. If it cannot, please elaborate on why it is core to this project and why you feel more than 80% of users would find this beneficial.

This issue will automatically be closed in two months if no further activity occurs. Thank you for all your contributions.

**Comment by DirtyF** [comment]
In YAML you have to specify a `null` value.

So if you declare this defaults in your `_config.yml` :

 ```yaml
defaults:
  - scope:
      path: ''
    values:
      description: null
```

All meta description (HTML, OPenGraph, JSON/LD)  are set to the default excerpt (the first paragraph in your Markdown file)

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least two months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider whether it can be accomplished in another way. If it cannot, please elaborate on why it is core to this project and why you feel more than 80% of users would find this beneficial.

This issue will automatically be closed in two months if no further activity occurs. Thank you for all your contributions.

**Comment by ahmetb** [comment]
@DirtyF your recommendation doesn't seem to be working. 

```yaml
defaults:
  -
    scope:
      path: ""
    values:
      description: null
...
```

Repro: https://github.com/ahmetb/kubernetes.github.io/commit/f4e7d12c5d4eeb474749d8cfdc59996725e97508
