### ISSUE TITLE
I can't get og:site_name to update to my custom URL

### ISSUE THREAD

**Issue by brett9897** [jekyll/jekyll-seo-tag#383]
My _config.yml is
```yml
url: https://learnfromit.co
tagline: My daily struggles with code
logo: /assets/images/favicon.png

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

github: [metadata]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Brett"
```
And in the head it is
`<meta property="og:site_name" content="brett9897.github.io">`
and if that isn't the property that updates, what does update that?

Also the tagline and logo aren't picked up either but that isn't a big deal.  Am I missing something?
