### ISSUE TITLE
Issue: tagline not honored, title becomes <title> | <description>

### ISSUE THREAD

**Issue by pixelicous** [jekyll/jekyll-seo-tag#411]
Hi,
I have the following files
head.html
```html
<head>
{% seo %}
</head>
```
(no other title in head)

index.html
```yaml
---
title: my title
layout: default
---
```

_config.yml
```yaml
title: my title
tagline: short description
description: >- 
  Some long description
  of my website here.
url: "https://www.website.net"
```

But i am getting the following title in my homepage "my title | Some long description of my website here."

I'd prefer only having the title without the tag line, that is what i tried first. That didn't work as well..
