### ISSUE TITLE
Language Tag not working

### ISSUE THREAD

**Issue by pagenstedt** [jekyll/jekyll-seo-tag#423]
I tried  
    locale: 
    language_TERRITORY: de_DE

and 
    locale: de_DE
but en_US will not be overwritten.

Instead I get an github error message. 
A bug or my fault?

**Comment by ashmaroli** [comment]
Based on *your commit history*, the error looks like to be from your end.
YAML is indentation sensitive. So meaning changes when a key is at the start of line and when it is preceded by two spaces, etc.
Additionally, the `language_TERRITORY` mention in the docs is just the *format* not an actual key or value.

Try the following:
```yaml
# in your _config.yml

permalink: pretty
locale: de_DE       # align key with an existing key
```
