### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by jekyllbot** [jekyll/jekyll-seo-tag#494]
Hello, maintainers! :wave:

By my calculations, it's time for a new release of jekyll-seo-tag. It's been over 2 months since the last release, [v2.8.0](https://github.com/jekyll/jekyll-seo-tag/releases/tag/v2.8.0).

What else is left to be done before a new release can be made? Please make sure to update History.markdown too if it's not already updated.

Thanks! :revolving_hearts: :sparkles:

**Comment by y377** [comment]
```yml
---
date: 2023-07-02
layout: collection_index
collection: networking
title: {{ site.collections.networking.index }}
---
```
I expect seo to handle Liquid tags and variables in Front Matter correctly, which it doesn't currently do, so I'm trying to use ai to help me "remodel" it, hopefully I'll be successful!
